### ISSUE TITLE
ModBus SetApp

### ISSUE THREAD

**Issue by Beukel** [djfanatix/com.solaredge#2]
How do I get access rights for the SetApp?

**Comment by djfanatix** [comment]
Switch the red switch.

Enable wifi direct on the inverter. 
Connect to the inverter access point like you would for a normal wifi network. 
The wifi password is published at the right side of the inverter. 
Then open up a browser and go to http://172.16.0.1 .
From this webpage you can enable modbus TCP without setApp or installer account.

**Comment by Beukel** [comment]
Ha stupid me. Did it and could switch on ModBus with port 502. Thank you. Set a fixed IP as well. But the app says "temporary unavailable". What could be wrong?

**Comment by djfanatix** [comment]
Does it say connected? (In the solaredge setapp)

Otherwise try a reboot of the Solaredge app.


Try the tricks - troubleshoots in the 2nd post of the homey community.

[link](https://community.athom.com/t/app-solaredge/45487)

**Comment by Beukel** [comment]
I tried, but I still get a screen without the values. Do I really need to do something with the RS485-2? I tried but this did not help either. I restarted the app, I restarted the inverter. I will wait a bit I think until a procedure has been found to start this up. Unless there is something crucial I missed.

**Comment by djfanatix** [comment]
You can always send me a diagnostics report, but my guess is it that will show nothing. 

You need to be sure that you are connected, the solaredge setapp should mention this.

**Comment by Beukel** [comment]
Yes I am connected in de setapp when I change things over there. In the homey app still no values and then “temporary unavailable”.  I always restart the homey app too.
