### ISSUE TITLE
Solaredge omvormer toevoegen aan homey

### ISSUE THREAD

**Issue by Lampje43** [djfanatix/com.solaredge#3]
Ik heb een solaredge SE3000H inverter welke werkt met de setting app.

Ik heb het ip adres ingegeven en de rest standard laren staan. Hij wil niet verbinden. Hebben jullie nog suggesties/tips?

**Comment by djfanatix** [comment]
Je kan best de readme lezen op de homey community.

je moet de modbus tcp ook activeren op je omvormer
