### ISSUE TITLE
Since 7.01 no communication with Solaredge device

### ISSUE THREAD

**Issue by SdeKoning** [djfanatix/com.solaredge#4]
Hi,

Since a week or so I can not communicate with my Solaredge over wifi any more.
Do you know if this communication problem is reported / related after the homey update?

Thanks

**Comment by djfanatix** [comment]
Can you send me a diagnostics report?

mine is still working fine on 7.1.0 rc3

**Comment by SdeKoning** [comment]
Hi,

Will this link help?

2b0c3cd6-2b0f-4ab8-a578-fff0522bb99a

Thanks for looking in to this.

mvg
Steef de Koning

________________________________

**Comment by djfanatix** [comment]
errno: 'ECONNREFUSED',
 code: 'ECONNREFUSED',
 syscall: 'connect',
 address: '192.168.1.18',
 port: 1502
 

i think a network or issue, or your inverter?
Is the ip correct? And settings correct

**Comment by SdeKoning** [comment]
Yes, I can ping the device and also the port is ok.

Strange. I will reset my router. Maybe that helps.

mvg
Steef de Koning

________________________________

**Comment by SdeKoning** [comment]
Hi,

I should have done it before:

I restarted my Netgear router and it is working again.
Sorry for any inconvenience , thanks for having some time to listen.

Regards Steef de Koning

mvg
Steef de Koning

________________________________
