### ISSUE TITLE
Unable to open config page during API connection failure

### ISSUE THREAD

**Issue by whvanderpost** [djfanatix/com.solaredge#5]
Hi,

Last weekend I had to do some maintenance in the fuse box at home so I cut the power for some hours, so everything was offline. Homey, WiFi, SolarEdge.
When I brought everything back online I noticed a red exclamation mark on the SolarEdge tile in the Homey App. On opening the app it showed an error on the API. When I opened the settings screen (gear icon) I got a black screen and was unable to get out of it. Only way was to forcefully close the Homey app. I've made a screencast:
https://user-images.githubusercontent.com/2821657/126325966-adf4cd1f-22b6-45ec-bff3-ffaa9c4b1641.mp4

After restarting the SolarEdge app within the Homey settings it was able to reach the API again and all was back to normal. So this problem is solved but maybe something to try and reproduce for future updates.

**Comment by djfanatix** [comment]
This is normal as the timestamp is not correct anymore, rebooting the app is the solution ;-) 

unable to get out of the black screen is a homey thing.

**Comment by whvanderpost** [comment]
> This is normal as the timestamp is not correct anymore, rebooting the app is the solution ;-)
> 
> unable to get out of the black screen is a homey thing.

I posted this after contacting homey.
This is what they said:

> Het issue dat je ervaart ligt helaas niet aan de Homey software, maar aan de community app die je gebruikt. Het beste wat je kunt doen is even contact leggen met de ontwikkelaar van deze community app zodat hij op de hoogte is dat zijn app niet goed werkt.

I guess we’re in a ‘from the closet to the wall’ situation now 😬

**Comment by djfanatix** [comment]
Haha, I don’t think it is a major problem.

I crashed the app a lot during development, and I could always close the window. 

To avoid issues in the future, you could make a flow that when Homey boots, it restarts the Solaredge app after +/- 15 minutes. (When your internet, network and inverter is running again after a power failure)
