### ISSUE TITLE
Device unavailable. Homey Pro 

### ISSUE THREAD

**Issue by mprovementdev** [djfanatix/com.solaredge#9]
Hi,

I have walked thru all the necessary settings. Still, I get the message. The device is unavailable. As far I can see. All the settings are correct. But maybe I overlooked something.

I have send diagnostic report via Homey: 69ae9c61-0df2-4a5a-9f9b-48f344bee3cb

Settings inverter:
![image](https://user-images.githubusercontent.com/31613642/146145254-14b558b9-4bd2-4f17-8c6b-293b25d51bfe.png)
Communication setting inverter:
![image](https://user-images.githubusercontent.com/31613642/146145341-5dd06ce5-2aad-4db3-b385-16e390803bf6.png)
Settings Device Homey:
![image](https://user-images.githubusercontent.com/31613642/146145410-cc849440-8cea-47c1-983f-3d06861c66c3.png)
Status Device Homey (Pro)
![image](https://user-images.githubusercontent.com/31613642/146145554-210e6b3f-9008-4870-ac2c-b81c55e9d699.png)

**Comment by djfanatix** [comment]
please try the following things:
- install the latest test version: https://homey.app/nl-be/app/solaredge.modbus/SolarEdge/test/
- Set Reconnect timeout to 60
- Restart Internet/ Router
- Restart Homey

Let app run for a few minutes and then send me a diagnostics report

Most of the connection problems are due to internet, routing issues.
Make sure your SolarEdge inverter has a fixed IP address

**Comment by djfanatix** [comment]
Ok, I see your diagnostics report, it is a connection issue.
Is the IP address correct? otherwise check in your router

**Comment by mprovementdev** [comment]
Settings Router:
![image](https://user-images.githubusercontent.com/31613642/146175411-5ac86e0b-3495-4252-862d-a8cba0f7fcb1.png)

**Comment by djfanatix** [comment]
Try to restart your inverter, sometimes this helps to connect.
Otherwise I don't know, it has nothing to do with the app, but networking.

**Comment by mprovementdev** [comment]
It's connected. And I see also a bit of traffic transferred. 
![image](https://user-images.githubusercontent.com/31613642/146175930-8bed27bb-13d8-4b48-b961-b07876c94729.png)

Have restarted The Homey. 
I'm ad work so for restarting the Inverter we have to wait... And I have figured out how to restart it.

**Comment by mprovementdev** [comment]
I have also installed the test version of the app..  But that also didn't help. So my last option is to restart the inverter. Hopefully, that will work. 

I'll keep you posted.

**Comment by djfanatix** [comment]
Some inverters with old firmware only want to connect by modbus tcp during the first minutes after starting

**Comment by mprovementdev** [comment]
My inverter is brand new... 1 week old, it should have the latest firmware. That's my assumption.

**Comment by mprovementdev** [comment]
@djfanatix sorry for my late response. Finally, I have found some time to troubleshoot. Yesterday I have tried everything. Full reset and restart inverter, restart homey, restart SolarEdge app, re-install SolarEdge app, change port from 1502 to 502, setup a' port forwarding rule in my router:
![image](https://user-images.githubusercontent.com/31613642/148920438-391df1fb-6262-413b-9df9-547b7ae83fdd.png)

Sadly enough, nothing works.

**Comment by djfanatix** [comment]
You could try to connect with an app like 'Modbus TCP'(iOS) to connect to your inverter, so you could see it is reachable or not

**Comment by mprovementdev** [comment]
I'll give it a try when I get back home.

**Comment by mprovementdev** [comment]
I have tried it with your suggested app. And indeed. The inverter is not reachable. I think to know what the issue is. The inverter is connected via WIFI. And if I read the inverter's manual regarding MODBUS. It says: 
https://www.solaredge.com/sites/default/files/sunspec-implementation-technical-note.pdf 
"MODBUS over TCP Support
MODBUS/TCP uses the Ethernet media in physical layers to carry the MODBUS message handling structure and can support a large number of devices in one network; it is easier to integrate into the Local Area Network (LAN) of a company, so it is the choice of more and more customers."

It looks like it only works via Ethernet.

**Comment by djfanatix** [comment]
there are other users who use the app with wifi, so it should work.
I guess it is a networking issue, (ip, ports, different vlan or so)

**Comment by mprovementdev** [comment]
I can ping the IP sddress from different devices (IOS, desktop) from the same Wifi network. That should say. It is reachable. I will contact the supplier lets see if they can help.
